### ISSUE TITLE
Not displaying all columns

### ISSUE THREAD

**Issue by Vishnu-S-Nair** [methnen/m-chart#103]
Hi,
Awesome work with the chart. I have a total entry of 30 items. The chart is skipping one item in between and showing only 15. Is there any way to change it so that all 30 columns with be displayed
Thankyou

**Comment by methnen** [comment]
Hey, I honestly can't say what might be happening here with out a CSV export of the data and a screenshot of the chart settings you're using. If you aren't comfortable sharing that publicly feel free to email me at jamie AT methnen.com

**Comment by methnen** [comment]
Closing since there's been no reply from the OP for a month.
