### ISSUE TITLE
Posts are broken

### ISSUE THREAD

**Issue by simardcasanova** [methnen/m-chart#106]
Hi,

First of all, I'd like to thank you for this extension, it's a great one!

I use M-Chart quite a lot on a WordPress-powered website. Unfortunately, the pages where I display graphs are now broken.

According to the Safari debug console, JQuery is missing. But I have no idea how to solve this issue.

Here's a page that doesn't work anymore: https://lesignal.info/chart/prix-de-la-tonne-dacier-entre-2012-et-2016

Any idea what could be the problem?

Olivier

**Comment by methnen** [comment]
Hey @simardcasanova,

Is the template your using for charts loading `wp_head();` ? I'm pretty sure that's where WordPress loads jQuery.

**Comment by methnen** [comment]
@simardcasanova did that point you in the right direction or are you still having trouble?

**Comment by methnen** [comment]
Closing since I've never received a reply on this.
