### ISSUE TITLE
Can't use Highcharts as library

### ISSUE THREAD

**Issue by Madic-** [methnen/m-chart#109]
Hello,

I've installed the m-chart-highcharts-library into the plugins folder and I can select it as library in the M Chart Settings. But when I create a new chart chart.js is used. Also when the default performance options are enabled I get the following errors in the browser console:

TypeError: window[(("m_chart_highcharts_" + m_chart_admin.post_id) + "_1")] is undefined
m-chart-highcharts-admin.js:112:3

TypeError: event.chart is undefined
m-chart-highcharts-admin.js:73:7

Do you have any idea?

Kind Regards,
   Madic

**Comment by methnen** [comment]
Hmm, I did a bunch of testing switching back and forth and I know I've got a fair number of users on the latest version who are also using Highcharts so I'm reasonably sure it's working for most people.

That first error is related to the Javascript attempting to tel thel Highcharts object that the settings object is ready for it to render the chart (like after a setting is changed but it does it once at the beginning too)

The second error I'd have to look at the code more closely to know for sure.  

But in both cases the implication is that the Javascript object that handles the rendering of the chart isn't there for some reason. 

Is this a completely fresh install or were you using M Chart before the latest version?

Is there any chance I could see this in action if you're comfortable temporarily giving me access to your site? Or if your host has a staging/development version that you can use then I could investigate that way. I'll also see if I can somehow replicate this issue on my end.

**Comment by Madic-** [comment]
I can create a duplicate of my environment on the weekend. When I'm ready I will update the issue.
So you can change every setting if you want to.

It's an update. Been using m chart since version 1.5

**Comment by methnen** [comment]
Great, that will be incredibly helpful. Feel free to email any details to me at:

jamie AT methnen.com

**Comment by Madic-** [comment]
I've sent you an email with login data. You can do whatever you want on the development side, (de)activating plugins, changing settings etc.
I already tested, if the problem occurs due to the caching methods (disabled them all) or PHP7.2 (reverted back to 7.1, still on 7.1)

**Comment by methnen** [comment]
Thanks appreciate the ability to see the problem in action first hand.  I will take a look at this as soon as I can. Might be Sunday or Monday before that happens though. Family stuff going on this weekend.

**Comment by methnen** [comment]
@Madic- thanks for the test setup. I believe I've identified the issue. I'll get a fix up as soon as possible.

**Comment by methnen** [comment]
OK, I just pushed version 1.7.1 to the Wordpress directory. It should be up soon.

@Madic- do let me know when you have a chance if this fixes the issue for you.

**Comment by Madic-** [comment]
Thank you. That fixed it for me. I can use the highcharts library again :)

**Comment by methnen** [comment]
Awesome.

Closing this issue since it's fixed.
