### ISSUE TITLE
Removes Page Content

### ISSUE THREAD

**Issue by Discman813** [methnen/m-chart#111]
Using MChart in Wordpress (https://alabamanurses.org/dashboard/). Latest version installed and site completely up to date. Recently the page with charts shows up white and content is removed. Everything visible on back end. Had to deactivate plugin to make page content visible again. Any fix for this bug?

Thanks!
Travis

**Comment by methnen** [comment]
@Discman813 I'd be happy to come up with a fix but this is the first I've heard of this happening. Is there a way I could login to your install to possibly see what might be happening? A staging or dev version of the site is fine too.

Feel free to email me at jamie AT methnen.com

**Comment by Discman813** [comment]
I did some more toying around and figured it out. Thank you!

**Comment by methnen** [comment]
Can you share what the issue was and how you fixed it? I'd love to know.

**Comment by Discman813** [comment]
Sure thing! I had to install MCharts Highlights Library. Apparently that was a recent change that I missed (and was right in front of me). Without it, it was corrupting the whole page.  ---- On Wed, 22 Aug 2018 08:36:52 -0600 Jamie Poitra <notifications@github.com> wrote ---- Can you share what the issue was and how you fixed it? I'd love to know. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by methnen** [comment]
Ah, ok. That makes sense to some extent though it shouldn't have corrupted the whole page. I'll have to look into why that was happening.

I tried to make that need so noticeable but you're the second person I know of who missed it so clearly I failed at that.

**Comment by Discman813** [comment]
LOL In your defense, I'm really bad about glossing over announcements (pop-up fatigue). I had my partner take a look this morning and he saw it right away. ---- On Wed, 22 Aug 2018 08:41:02 -0600 Jamie Poitra <notifications@github.com> wrote ---- Ah, ok. That makes sense to some extent though it shouldn't have corrupted the whole page. I'll have to look into why that was happening. I tried to make that need so noticeable but you're the second person I know of who missed it so clearly I failed at that. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by methnen** [comment]
Good to hear. I'm sorry about the change being so disruptive, it wasn't something I had much of a choice about if I wanted to get the plugin back on the Wordpress website but I do realize how annoying it is to have that functionality split out into a separate plugin.

**Comment by methnen** [comment]
Closing since it's old news now.
