### ISSUE TITLE
Generated Images With Highcharts Plugin Cropped Incorrectly

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#112]
Image files created using the Highcharts plugin seem to be rendering overly large and end up cropped. Here's an example:
![2018-annual-temperatures-6767](https://user-images.githubusercontent.com/3456575/44437944-6abe7b80-a582-11e8-9f18-8e5a1e51bf7a.png)

I'm using the latest m-chart and m-chart-highcharts-library.

**Comment by buffaloseven** [comment]
You can see more examples on [my climate archive](https://www.aweathermoment.com/climate/) webpage. The July/August charts were created with the new version of m-chart with the highcharts plugin. June and earlier were created with m-chart 1.5.1 I believe.

**Comment by methnen** [comment]
Hmm Highcharts must have changed something again. I’ll take a look at this tomorrow morning.

**Comment by buffaloseven** [comment]
Thanks!

**Comment by methnen** [comment]
@buffaloseven I just pushed an update that I believe fixes the issue. 

Let me know if that solves things for you.

**Comment by buffaloseven** [comment]
Tested on my setup and the images now work correctly.

**Comment by methnen** [comment]
Closing since this bug has been fixed.
