### ISSUE TITLE
Ability to export PNG/PDF/XLS ?

### ISSUE THREAD

**Issue by pranay227** [methnen/m-chart#113]
Is it possible to add the ability to download png/PDF/excel export of the chart- for the front end user? I know it is a feature in high-charts but I am not sure how to implement this on the plugin
![screen shot 2018-08-21 at 7 25 20 pm](https://user-images.githubusercontent.com/12129199/44439328-ff6fac00-a577-11e8-8728-ed1fa0f9a01d.png)

**Comment by methnen** [comment]
If you want to use Highcharts exporting stuff you'll need to include some additional scripts on the front end:

https://www.highcharts.com/docs/export-module/export-module-overview

You can then activate those features either via adding a filter to the [m_chart_chart_args](https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks#m_chart_chart_args) filter hook, OR you could use the [theme](https://github.com/methnen/m-chart/wiki/Themes) functionality which sort of works as an abstracted filter hook.

**Comment by buffaloseven** [comment]
If you're using a theme, just add:

```php
'exporting' => array(
		'enabled' => true
	),
```

Perhaps relatedly, @methnen: is there a chance we could get an option when using Highcharts in the m-chart settings to include `export-offline.js` to keep things local instead of using the Highcharts export server?

**Comment by methnen** [comment]
Yes, I could include that as a registered script in the plugin. I'll add that in next time I push an update.

**Comment by benzien** [comment]
Hey all-

I tried adding this to my theme footer: 
<script src="/public_html/wp-content/plugins/m-chart-highcharts-library/components/external/highcharts/exporting.js"></script>

and the code in the comment from @buffaloseven above into my theme, but I'm not getting the exporting button on my charts. Any guidance?

You can find a test chart here: https://www.solarpowerrocks.com/affordable-solar/mo-test-charts/ 

Also any guidance as to whether my hacked logo set as a background image in the x-axis label will come through in export with allowHTML enabled would be appreciated!

**Comment by benzien** [comment]
Actually I solved this with help from a friend. Just had to remove /public_html/ and put the script at the end of the footer. 

I do still need help with logo on chart output, but I'll start a new issue for that one.

**Comment by methnen** [comment]
Closing since this has been resolved.

**Comment by methnen** [comment]
Also meant to mention that the next version of the Highcharts Library that I'll be pushing live sometime this month will have some additional libraries already registered so you'll be able to enqueue things like the exporting stuff more easily.
