### ISSUE TITLE
Can't publish chart

### ISSUE THREAD

**Issue by wixosk** [methnen/m-chart#114]
Hi, I'm using M Chart 1.7.1 on WP 4.9.8. and I can't save any new chart. Publish button is disabled and chart preview is not generated. Even on clean install without any plugins activated, while using default theme. Thanks for the help.

**Comment by methnen** [comment]
That typically means a JS error of some kind. Do you see anything in the browser console?

**Comment by wixosk** [comment]
SyntaxError: Unexpected token '<' on post.php:514 
and 
TypeError: undefined is not an object (evaluating 'window[ 'm_chart_chartjs_' + m_chart_admin.post_id + '_1' ].chart') at m-chart-chartjs-admin.js:105

**Comment by methnen** [comment]
That's similar to what someone else was receiving in the previous version. I'll see if I can duplicate it locally. If I can't is there a chance I could investigate on my own install?

**Comment by methnen** [comment]
Closing since 1.7.2 fixes this issue.
