### ISSUE TITLE
[Request/Help] Creating Dual-Axis Charts

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#116]
For some data, having a dual-axis chart still remains the best way to present the information. This request will focus on using Highcharts integration.

With Highcharts, it's relatively easy to implement *n*-y-axis charts by setting the yAxis chart setting to be an array of objects defining the y-axes. With m-chart, it appears that the theming setup will only return elements into the `plotOptions` element of the chart configuration. This makes it impossible to create dual-axis charts.

What I would like to see is *some* way of working around this. Be it a filter that I could apply within my theme for the particular kind of chart I want to have multiple axes, a modification to how themes are applied within the core plugin (probably not a good idea), or a native control in the GUI/core.

If there's a filter solution, some guidance in how to achieve it would be appreciated, I've not quite been able to figure it out thus far.

For what it's worth, my current theme code follows:

```php
<?php

/**
 * Theme Name: Daily Precipitation by Year
 */

return array(
	'chart' => array(
		'zoomType' => 'x'
	),
	'colors' => array(
		"#669774",
		"#2C5298",
		"#ADADAD"
	),
    'tooltip' => array(
        'shared' => true,
		'valueSuffix' => 'mm'
	),
	'yAxis' => array(
		array(
			'title' => array(
				'text' => "Daily Accumulation (mm)"
			),
			'tickAmount' => 5
		),
		array(
			'title' => array(
				'text' => "Yearly Accumulation (mm)"
			),
			'tickAmount' => 5
		)
	),
	'series' => array(
		array(
			'type' => 'column',
			'zIndex' => 1
		),
		array(
			'lineWidth' => 3,
			'marker' => array(
				'enabled' => false
			),
			'shadow' => true,
			'yAxis' => 1,
			'zIndex' => 2
		),
		array(
			'dashStyle' => 'ShortDashDot',
			'lineWidth' => 2,
			'marker' => array(
				'enabled' => false
			),
			'shadow' => false,
			'yAxis' => 1,
			'zIndex' => 0
		)
	)
);
 ?>
```

**Comment by methnen** [comment]
@buffaloseven Just wanted to reply that I have been putting some thought into this.

I haven't tested this theory but I think you should be able to run a function on the `m_chart_chart_args` filter hook. From within your theme. Something like this:

```php
<?php

/**
 * Theme Name: Daily Precipitation by Year
 */

add_filter( 'm_chart_chart_args', 'm_chart_daily_precipitation_by_year_chart_args', 10, 4 );

function m_chart_daily_precipitation_by_year_chart_args( $chart_args, $post, $post_meta, $args ) {
	// Do your manipulation on the $chart_args array here
	
	return $chart_args;
}

return array(
	'chart' => array(
		'zoomType' => 'x'
	),
	'colors' => array(
		"#669774",
		"#2C5298",
		"#ADADAD"
	),
    'tooltip' => array(
        'shared' => true,
		'valueSuffix' => 'mm'
	),
	'yAxis' => array(
		array(
			'title' => array(
				'text' => "Daily Accumulation (mm)"
			),
			'tickAmount' => 5
		),
		array(
			'title' => array(
				'text' => "Yearly Accumulation (mm)"
			),
			'tickAmount' => 5
		)
	),
	'series' => array(
		array(
			'type' => 'column',
			'zIndex' => 1
		),
		array(
			'lineWidth' => 3,
			'marker' => array(
				'enabled' => false
			),
			'shadow' => true,
			'yAxis' => 1,
			'zIndex' => 2
		),
		array(
			'dashStyle' => 'ShortDashDot',
			'lineWidth' => 2,
			'marker' => array(
				'enabled' => false
			),
			'shadow' => false,
			'yAxis' => 1,
			'zIndex' => 0
		)
	)
);
```

Also small tip. It's generally safer to leave the ?> off the end of a PHP file. Prevents accidental whitespace insertion into your page which can cause issues that can be basically impossible to track down.

**Comment by methnen** [comment]
Well, nix that. That doesn't work at all because the function will get redeclared too many times and even worse will probably pick in even when the theme isn't active.

Let me think a bit more.
