### ISSUE TITLE
Dynamic filenames using Highcharts exporting

### ISSUE THREAD

**Issue by benzien** [methnen/m-chart#125]
Hi there! 

One of the final customizations I'd like to make to the chart output is use the chart title as the filename when the chart is exported for download by the highcharts library. I've been able to get the exporting function to work great within a custom theme.php file, but because I want to use the post title as the filename, I removed exporting from the theme and tried to use m_chart_args hook in functions.php. 

I prepared the following code, but despite all attempts at formatting it properly, it causes the chart to not display on the page:

	function m_chart_chart_args( $chart_args, $post, $post_meta, $args ) {

		$chart_args['exporting'] = array(

				'enabled' => true,

				'allowHTML' => true,

				'filename' => $post->post_title,

				'buttons' => [

					'contextButton' => [

						'menuItems' => array(

							'downloadPNG'

						),

					]

				]

			);

			return $chart_args;

		}

	add_filter( 'm_chart_chart_args', 'filter_m_chart_chart_args', 10, 4 );

Any advice to getting this to work?

**Comment by methnen** [comment]
If the chart isn't displaying you should be getting a JS error of some kind on in the browser console. What's that error say?

**Comment by benzien** [comment]
Sorry for the delay. 

I found this message in the sources pane of Chrome's devTools:

<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, function 'filter_m_chart_chart_args' not found or invalid function name in <b>/home/benz2396/public_html/wp-includes/class-wp-hook.php</b> on line <b>298</b><br />

**Comment by benzien** [comment]
Here's the relevant portion of class-wp-hook.php:

	public function apply_filters( $value, $args ) {
		if ( ! $this->callbacks ) {
			return $value;
		}

		$nesting_level = $this->nesting_level++;

		$this->iterations[ $nesting_level ] = array_keys( $this->callbacks );
		$num_args = count( $args );

		do {
			$this->current_priority[ $nesting_level ] = $priority = current( $this->iterations[ $nesting_level ] );

			foreach ( $this->callbacks[ $priority ] as $the_ ) {
				if( ! $this->doing_action ) {
					$args[ 0 ] = $value;
				}

				// Avoid the array_slice if possible.
				if ( $the_['accepted_args'] == 0 ) {
					$value = call_user_func_array( $the_['function'], array() );
				} elseif ( $the_['accepted_args'] >= $num_args ) {
					$value = call_user_func_array( $the_['function'], $args );
				} else {
					$value = call_user_func_array( $the_['function'], array_slice( $args, 0, (int)$the_['accepted_args'] ) );
				}
			}
		} while ( false !== next( $this->iterations[ $nesting_level ] ) );

		unset( $this->iterations[ $nesting_level ] );
		unset( $this->current_priority[ $nesting_level ] );

		$this->nesting_level--;

		return $value;
	}

line 298 is this line:

	$value = call_user_func_array( $the_['function'], $args );

**Comment by methnen** [comment]
@benzien that error is something I should have noticed when you first shared your code above. Your function name needs to match the call back you indicate in the filter call.

Instead of this:

`function m_chart_chart_args( $chart_args, $post, $post_meta, $args ) {`

Make it this:

`function filter_m_chart_chart_args( $chart_args, $post, $post_meta, $args ) {`

**Comment by benzien** [comment]
It works!

Thank you!

**Comment by methnen** [comment]
Closing as the issue was resolved.
