### ISSUE TITLE
How to change font color and font size

### ISSUE THREAD

**Issue by robertocastroserantes** [methnen/m-chart#130]
Hello, how can I change font color and font size in the x-Axes and Y-Axes?

**Comment by methnen** [comment]
If you are using the Highcharts library:

https://api.highcharts.com/highcharts/xAxis.labels.style
https://api.highcharts.com/highcharts/yAxis.labels.style

You would need create a custom theme and add your styles to that:

https://github.com/methnen/m-chart/wiki/Themes

Optionally you could set styled mode to true (through a theme or a filter hook on the chart args:

How styled mode works:

https://www.highcharts.com/docs/chart-design-and-style/style-by-css

If you are using the Chart.js stuff you'd need to run a filter hook against the chart args hook and modify them to add the font and style changes you want.

Filter hook you'd want to deal with:

https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks#m_chart_chart_args

Chart.js axis docs:

https://www.chartjs.org/docs/latest/axes/styling.html
