### ISSUE TITLE
Uninstall m-chart and highcharts and then re-install m-chart not working

### ISSUE THREAD

**Issue by feralreason** [methnen/m-chart#138]
After getting this working in a test site with m-chart and highcharts, I uninstalled both plugins and reinstalled m-chart by itself. After this I could not get a display of the chart in the edit function. Additionally, I could not publish a chart. 

A number of records from the plugin remained in the database: 
**wp-options:**  m-chart, m-chartunits_children, m_chart_version.
**wp_posts:** A record for each chart created.
**wp_postmeta:** records associated with posts (meta-keys: m-chart-image and m-chart.)
**wp-terms:**  highcharts, chartjs,
**wp-term-taxonomy:** taxonomy = m-chart-units and m-chart-library
**wp-term-relationships** - records associated with a number of the wp_term_taxonomy_ids found in wp-term-taxonomy table.

I deactivated / deleted the m-chart plugin again. 
Then removed these records, taking care to try to get all associated records. 

I then reinstalled the m-chart plugin, and am still getting the same effect in the edit function -- the charts will not display and I cannot "Publish". 

Additionally, I am getting 44 messages in the console. All similar to these:

_load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.2:8 JQMIGRATE: Migrate is installed, version 1.4.1
edit.php?post_type=m-chart:1 [DOM] Found 2 elements with non-unique id #in-category-1: (More info: https://goo.gl/9p2vKq) <input value=​"1" type=​"checkbox" name=​"post_category[]​" id=​"in-category-1">​ <input value=​"1" type=​"checkbox" name=​"post_category[]​" id=​"in-category-1">​
edit.php?post_type=m-chart:1 [DOM] Found 2 elements with non-unique id #in-category-3: (More info: https://goo.gl/9p2vKq) <input value=​"3" type=​"checkbox" name=​"post_category[]​" id=​"in-category-3">​ <input value=​"3" type=​"checkbox" name=​"post_category[]​" id=​"in-category-3">​
edit.php?post_type=m-chart:1 [DOM] Found 2 elements with non-unique id #in-category-_

These are more or less repeated as warnings.

Finally, I reinstalled M Chart (only) in a second test site running the same WordPress version: 5.3.2.  This install works fine.

Generally, I love the plugin and am anxious to get m-chart alone back up and running on the first site.  Pls let me know know if you have any ideas.

**Comment by methnen** [comment]
Hey! I will probably have some time to look at this tomorrow. It’s always easiest to debug these sorts of things if I can see the issue in action. Is there any chance the site you are working on is accessible to me in some way?

Feel free to email any more private details:

jamie AT methnen.com

**Comment by feralreason** [comment]
Methen -- My bad. 

I was trying to solve the "set the Vertical Axis Minimum to 0 without Highcharts" and I failed to delete part of my test code.  That's what caused the problem.  Things seem back to normal.

**Comment by feralreason** [comment]
Jamie,

 

Replied on GitHub  -- dumb mistake on my part. Failed to delete all my test code.

 

I think you really have a promising plugin in M Chart!  After a couple more minor features (e.g. set the vertical axis minimum), you might think about an M Chart Pro version  – strictly with chart.js -  to offer something more affordable than the highcharts solution.  Doesn’t seem like there is much competition in this space yet.

 

Thanks for your quick response!

 

Glenn Ferrell

**Comment by methnen** [comment]
Hey Glen,

Yeah, I can't say I'm terribly happy with the Chart.js limitations at this point. 

However, many of them are a result of Chart.js itself. 

It's just not as mature as Highcharts is and that results in some really disappointing tradeoffs and limitations.

Even the way colors are handled in Chart.js is simply atrocious which makes some of the features I have in Highcharts like themes basically impossible.

I'm hoping that it gets some continuing development though that will improve on those limitations over time.

That said, I also couldn't find any other solutions that were as good that were also GPL license compatible.

If you know of one I'd be interested in investigating it for sure.

One thing that having to separate Highcharts from the original plugin forced me to do was to abstract out the graphing library enough that switching to a different one shouldn't be quite the Herculean task it was the first time.

As for a M Chart Pro, I'll probably never do that. I have a full time job and work on this as hobby essentially and don't feel comfortable charging money despite the fact that I do attempt to provide everyone who does use it with a reasonable amount of support.

**Comment by feralreason** [comment]
Understood. I’ll keep my eyes open. My charts are simple so M-chart almost fits the bill  - and I like the “dynamic” look and feel.

Agree that better color control would be a ‘nice-to-have’.

 

Glad you’re employed full time – you seem to have the talent and the passion for this.

(It’s a great time for West Coast software engineers - my sons work at Waymo and PostMates.)

 

Have a great New Year!

 

Glenn Ferrell

 <mailto:glenn@gfwebsoft.com> glenn@gfwebsoft.com

**Comment by feralreason** [comment]
One last thing – I assume you have looked at Chartist : https://gionkunz.github.io/chartist-js/

And this comparison: https://buttercms.com/blog/comparing-javascript-charts-2019 

Chartist supports css for color control and uses svgs but many (what should be standard) features require extra plugins.

 

   Glenn

 

 <mailto:glenn@gfwebsoft.com> glenn@gfwebsoft.com

From: glenn@gfwebsoft.com <glenn@gfwebsoft.com> 
Sent: Monday, December 30, 2019 11:28 AM
To: 'methnen/m-chart' <reply@reply.github.com>
Subject: RE: [methnen/m-chart] Uninstall m-chart and highcharts and then re-install m-chart not working (#138)

 

Understood. I’ll keep my eyes open. My charts are simple so M-chart almost fits the bill  - and I like the “dynamic” look and feel.

Agree that better color control would be a ‘nice-to-have’.

 

Glad you’re employed full time – you seem to have the talent and the passion for this.

(It’s a great time for West Coast software engineers - my sons work at Waymo and PostMates.)

 

Have a great New Year!

 

Glenn Ferrell

 <mailto:glenn@gfwebsoft.com> glenn@gfwebsoft.com

**Comment by methnen** [comment]
I have a vague memory of looking at that one. But I honestly don't remember why I didn't go with it. :)

I like that's it uses the MIT license though which is the one my own plugin uses.

I'll try giving it another look when I've got some free time and am not in the midst of a bad cold. :)

**Comment by feralreason** [comment]
One more last thing :p

 

DS.js (https://d3js.org/) is perhaps more promising  –  altho more complex -- than Chartist: https://www.slant.co/options/10577/~d3-js-review

 

From: glenn@gfwebsoft.com <glenn@gfwebsoft.com> 
Sent: Monday, December 30, 2019 12:22 PM
To: 'methnen/m-chart' <reply@reply.github.com>
Subject: RE: [methnen/m-chart] Uninstall m-chart and highcharts and then re-install m-chart not working (#138)

 

One last thing – I assume you have looked at Chartist : https://gionkunz.github.io/chartist-js/

And this comparison: https://buttercms.com/blog/comparing-javascript-charts-2019 

Chartist supports css for color control and uses svgs but many (what should be standard) features require extra plugins.

 

   Glenn

 

 <mailto:glenn@gfwebsoft.com> glenn@gfwebsoft.com

From: glenn@gfwebsoft.com <mailto:glenn@gfwebsoft.com>  <glenn@gfwebsoft.com <mailto:glenn@gfwebsoft.com> > 
Sent: Monday, December 30, 2019 11:28 AM
To: 'methnen/m-chart' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [methnen/m-chart] Uninstall m-chart and highcharts and then re-install m-chart not working (#138)

 

Understood. I’ll keep my eyes open. My charts are simple so M-chart almost fits the bill  - and I like the “dynamic” look and feel.

Agree that better color control would be a ‘nice-to-have’.

 

Glad you’re employed full time – you seem to have the talent and the passion for this.

(It’s a great time for West Coast software engineers - my sons work at Waymo and PostMates.)

 

Have a great New Year!

 

Glenn Ferrell

 <mailto:glenn@gfwebsoft.com> glenn@gfwebsoft.com

**Comment by methnen** [comment]
Yeah, I know I've looked at that one before. The problem there is it's super complex, super powerful, but also not straightforward to implement. A lot of the things that a library like Chart.js and Highcharts does for you d3js requires you to essentially build yourself.

It's worth looking at again too though. Maybe some things have changed in that department since I last looked at it a few years ago.
