### ISSUE TITLE
Dynamic data

### ISSUE THREAD

**Issue by piersky** [methnen/m-chart#139]
Hi,
is it possible to update a graph whenever the data changes? Is there a hook or a function that we can use?

Thanks in advance.
Best regards.

**Comment by methnen** [comment]
There's an action hook that you could use to modify the chart data on the fly:

https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks#m_chart_chart_args

But there's no built in mechanism for doing this obviously. You'd have to build something on top of that action hook.

**Comment by piersky** [comment]
So, the hook can update the chart whenever in the admin panel is opened the graph?

My need is to update the frontend page due to data changing.

Thanks again.

**Comment by methnen** [comment]
No, you misunderstand.

The last paragraph was simply making sure that you understood that the data for an embedded chart automatically updates whenever you update the chart already. That's just how the plugin works.

But if you want to modify a chart in any way at the time it renders that action hook I pointed to will allow you to do that.
