### ISSUE TITLE
JQuery issue

### ISSUE THREAD

**Issue by kaarec** [methnen/m-chart#140]
Installed m chart and your highchart add-on yesterday. In the site admin area I've entered data for a line chart and it shows up perfectly in the chart area below the data table. It's obviously using js, as the lines are animated. But when I put the shortcode into a shortcode block (gutenberg) and display the page, nothing but blank space.  FF Console complains JQuery is not defined. WP 5.4 (just out yesterday) and the TwentyTwenty theme 1.2 (yesterday). https://bit.ly/2JxRdCO

**Comment by methnen** [comment]
@kaarec Does this blank occur on both the back end and the front end?

I can take a look at this today and will see if I can reproduce the issue.

**Comment by kaarec** [comment]
Wow thank you. I started the website yesterday morning, using wordpress
5.3.something and twentytwenty theme 1.1, but by afternoon both had
updated, wp to 5.4 and twenty twenty to 1.2. Made a few tiny tweaks to
2020, but basically this is a super fresh install. Only other plugins are
updraft for backups, tiny mce, wp forms, and wp super cache.

Browsing around, I found an interaction between another plugin  author and
the twenty twenty theme authors relating to jquery. The theme authors say
that they don't use jQuery, but that it works fine and plugins are welcome
to use it.

Attached the csv, tho it looks fine to me...

Perhaps these screen shots will help. Grabbed both at 50% to keep it
smallish:

The actual published page:
[image: image.png]

Chart editor:
[image: image.png]

**Comment by methnen** [comment]
Your images didn't make it through, but if you want to email me at jamie AT methnen.com you can send them that way.

So I tried duplicating this issue and can't seem to duplicate it at least with the default install I'm running.

Here you can see I've got a chart embed code inserted into the Gutenberg edit form:
https://methnen-dropshare.s3.amazonaws.com/pb-CMUgwCYybY.png

And here's the resulting page with the Highcharts form showing:
https://methnen-dropshare.s3.amazonaws.com/pb-NbxYOuFwLF.png

I'll see if installing any of the plugins you've got running next will duplicate the issue.

**Comment by methnen** [comment]
@kaarec which tiny ice plugin are you using? There's quite a few out there. Same for the wp forms plugin there's a lot of stuff by them.

I've added the updraft and wp cache plugins and still no issues.

**Comment by kaarec** [comment]
I disabled every plugin other than your two, and still have the issue.
About to resend screen shots to  you other email.

**Comment by methnen** [comment]
This was solved off the thread.

However, the workaround solution for this is to turn on iframe embeds in the settings. 

I'm looking into an actual bug fix. But essentially the twenty-twenty theme seems to prevent jQuery from being enqueued on the page.
