### ISSUE TITLE
user-editable graphs

### ISSUE THREAD

**Issue by Rik44444** [methnen/m-chart#142]
hi,
I'd like our website visitors to be able to edit the graphs on our site by A) changing the range of the x-axis and B) changing a number that feeds into the data underlying the graph?
Would this be possible with M Chart?
yours sincerely, 
Rik

**Comment by methnen** [comment]
Highcharts is pretty heavily extensible and there's lot of examples on their site of things like that if you're using the Highcharts plugin with it. That kind of interaction would be driven on the front end though so isn't really pertinent to M Chart in particular.

The default library Chart.js is less extensible but it does have some stuff that might allow for what you want to do.

None of this is core functionality though so you'd want to look at the documentation for whichever charting library you're using.
