### ISSUE TITLE
Need M Chart in update

### ISSUE THREAD

**Issue by ProNoiser** [methnen/m-chart#143]
Hello!
After updating WP to version 5.5, the preview of graphs and charts stopped showing in the plugin admin panel, and CSV import stopped working.
When is it expected to update the plugin with these bugs?
Thank.

**Comment by methnen** [comment]
Thanks for letting me know there's a problem. I'm looking into this right now and I'll update you once I have an idea.

**Comment by methnen** [comment]
@ProNoiser I'm seeing an issue where the data sent back when doing live previews is being messed up so it doesn't reflect the actual chart settings. Is this what you were seeing?

**Comment by methnen** [comment]
This is addressed in the two pull requests mentioned above. I'll be pushing these updates live shortly.
