### ISSUE TITLE
@ProNoiser I'm seeing an issue where the data sent back when doing live previews is being messed up so it doesn't reflect the actual chart settings. Is this what you were seeing?

### ISSUE THREAD

**Issue by ProNoiser** [methnen/m-chart#145]
Yes. For example, when switching to any chart view, a line chart is always displayed. Only when the chart is refreshed, the correct chart type is shown for a split second, but then the linear chart is shown again ... You have to work blindly. And the CSV-files have also stopped loading. Thanks.

**Comment by methnen** [comment]
@ProNoiser Did the version I launched last night not fix this issue?
