### ISSUE TITLE
PHP 7.4 not compatible with M Chart

### ISSUE THREAD

**Issue by ReHWolution** [methnen/m-chart#147]
Hello Mr. J! Sorry to bother you once again: I tried to activate PHP 7.4.9 but it seems like M Chart stops working when I do so. Rolling back to 7.3.x it works back again. Is there some function getting deprecated with this new version of PHP?

Thanks in advance!

**Comment by methnen** [comment]
Ciro!

I've tested with 7.4.2 and not seen any issues.

What exactly is happening? Are there any JS errors showing in the browser console? Howe about some PHP errors I the log?

I'll see if I can get a copy of PHP 7.4.9 going on my test setup to see if I can replicate any issues in the meantime.

**Comment by methnen** [comment]
@ReHWolution did you have a chance to look at your logs for any actual PHP errors?

**Comment by ReHWolution** [comment]
Hi methnen,

it seems like it’s not your plugin, but my theme to be bugged. After WP 5.5 it seems like they f’d up a lot of things…

Now I’m running 7.4.9 and charts work with no issues. Sorry for bothering you!

 

 

Da: Jamie Poitra <notifications@github.com> 
Inviato: mercoledì 26 agosto 2020 00:05
A: methnen/m-chart <m-chart@noreply.github.com>
Cc: ReHWolution <ciro.sdino@rehwolution.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [methnen/m-chart] PHP 7.4 not compatible with M Chart (#147)

 

@ReHWolution <https://github.com/ReHWolution>  did you have a chance to look at your logs for any actual PHP errors?

**Comment by methnen** [comment]
Ah, good to hear it wasn't on my end. :)
