### ISSUE TITLE
request - generate different radar charts using the same chart object with multiple sheets

### ISSUE THREAD

**Issue by liyuchang** [methnen/m-chart#154]
Hi there, I was wondering if you can make a new feature to let the user can select which data set (sheet) to display in a radar chart for a chart object which contains multiple sheets. It's also good to have the ability to manually set the min and max values of the radar chart.

**Comment by methnen** [comment]
I somehow missed this earlier. You can hide/show data sets by clicking on their name in the legend. Is this what you're asking for?

**Comment by methnen** [comment]
Closing for now follow up from OP.
