### ISSUE TITLE
Support for stacked columns/bars/areas

### ISSUE THREAD

**Issue by teatall** [methnen/m-chart#157]
It's a wonderful plugin. Please enable the support for stacked columns/bars/areas. Those are really needed.

Thank you!

**Comment by methnen** [comment]
Hey @teatall you're in luck, the next version is in development and I already activated the stacked columns/bars stuff.

I did not do it for area charts though as they're broken in the current Chart.js release in that the axis don't reflect the chart properly when you stack area/line charts.

It's something they've already been working on fixing so I can see it being added in at some later point.

When will that next version be released? Who knows? I do this for fun and my paying job sometimes gets in the way. It's close to being ready though.

**Comment by teatall** [comment]
Thanks and it's wonderful!
