### ISSUE TITLE
Update 1.9 Crashing Post Edit

### ISSUE THREAD

**Issue by 1user4life** [methnen/m-chart#160]
Update 1.9 is crashing wordpress when you try to load a post to edit. Disabling the plugin fixes the problem. Forces attempted recovery screen in wordpress.

Error:

The editor has encountered an unexpected error.                [Attempt Recovery][Copy Post Text][Copy Error]

Copy Error Option:

TypeError: r.media is not a function
    at new m 
    at fh 
    at Ch 
    at Pj 
    at di 
    at Nj 
    at sc 
    at gf 
    at
    at unstable_runWithPriority

**Comment by methnen** [comment]
@1user4life I somehow completely missed this but I'm seeing it now too. 

You mean specifically that it's crashing the block editor correct?

**Comment by methnen** [comment]
OK, I've identified the issue I should have a fix out shortly.

**Comment by methnen** [comment]
Fix is out. Please let me know if this fixes things for you?

**Comment by 1user4life** [comment]
You da man! 

It appears to be working without issue again. Block editor is not showing any signs of issue.
