### ISSUE TITLE
Axis labels not correct

### ISSUE THREAD

**Issue by teatall** [methnen/m-chart#163]
Hi, thank you for updating the plugin. It's wonderful to support stacked bars/columns now.

By any change that anyone is also noticing that if the lables of the parsed data are years (e.g., 2011, 2012, 2013, 2014 .....), they would not display correctly on the axis? I'm only getting 0, 1, 2, 3, 4 ... as the labels. Version 1.8 (at both front and back end) and 1.9.1 (frontend, not the backend) worked, but version 1.9 and 1.9.1 are not.

Strange enough is that these labels would be displaying correctly in the popover labels.

Thank you!

**Comment by methnen** [comment]
Hey @teatall , I think I might have an inkling of what's happening. Could you export your CSV and send it to me along with a screenshot of the chart settings and I'll take a look.

jamie AT methnen.com

**Comment by methnen** [comment]
I believe I've got a fix for this. Update should go out today.

**Comment by teatall** [comment]
Thank you!
