### ISSUE TITLE
406 Error Message when saving Chart

### ISSUE THREAD

**Issue by simonmueck** [methnen/m-chart#166]
Hi there, I ran into a problem after installing the plugin on my wordpress site. 
When trying to save a new / edited Chart I get an error message from my webhost. Error 406 - Not Acceptable (Safety Issue)

![grafik](https://user-images.githubusercontent.com/71900957/153732471-cef17228-d896-48c2-949b-820141380c84.png)

After getting the message I can jump back or reopen the Chart - all edits are gone (its basically a new chart). 

I ran into the same issue with other themes as well. Unfortunately I have no clue what is causing the problem. I hope you can help me with his :)

Cheers,
Simon

**Comment by methnen** [comment]
@simonmueck id I’d be happy to take a look but this is definitely one of those situations where I likely need to see it in action as I’ve never seen that error in relation to the plug-in. I’m thinking it might be hosting specific. 

Feel free to email me at jamie AT methnen.com with any details you can provide and let me know if you’d be comfortable with giving me access to see the issue in your install.

**Comment by methnen** [comment]
@simonmueck Just wanted to follow up and see if that indeed fixed the issue?

**Comment by simonmueck** [comment]
Sorry for getting back to you this late. Thank you for the suggestion, unfortunately turning of the image generation did not work. I'm in contact with my host - trying to pinpoint what is causing this issue. I'll write you once I have more information :)

**Comment by methnen** [comment]
Sorry to hear that didn't fix it. 

This error does seem to be very host specific from what I've seen just researching a bit on the web clearly something's triggering some security measure on the server side.

I figured it was the image binary being submitted with the chart settings but it must be something else.

If your host can determine what's happening I'd live to find out or if there's a way I could duplicate it myself that would probably help too.

What host are you using?

**Comment by methnen** [comment]
Closing for no followup from OP.
