### ISSUE TITLE
How to add a new JS chart library.

### ISSUE THREAD

**Issue by sajidmanzoor10p** [methnen/m-chart#168]
How to add a new JS chart library in M-charts plugin. Is there any action/filter hook available for that. or Is there any guide available for adding a new JS chart library?

**Comment by methnen** [comment]
@sajidmanzoor10p I'm not sure how I missed this question for so long.

There is no guide. You can look at the highcharts library to see how I did it there but that's the only living example and building a framework or documentation for that is not on the horizon given the kind of time I have to work on things. Bug fixes and new features have priority.
