### ISSUE TITLE
Chart Not Displaying Correctly

### ISSUE THREAD

**Issue by McCoyCOREUSA** [methnen/m-chart#173]
Trying this out and my first chart isn't displaying correctly. It looks fine in the preview and also in the generated image, but the short-code version isn't correct. The columns are thin. They start thick as the chart animation runs, but they go thin and stop. I'm unable to find any settings or other reasons this might be happening. Any help?
![2023-02-20_09-38-17](https://user-images.githubusercontent.com/104024793/220148970-5af02009-4baf-4ffd-9a4a-3f4e06dae196.jpg)

**Comment by McCoyCOREUSA** [comment]
Trying other chart types and they have the same type of issue. Very strange. I'm not finding any settings that might impact this issue....
![2023-02-20_09-43-41](https://user-images.githubusercontent.com/104024793/220149959-612d8a7a-8522-443b-9ddf-111878eda24a.jpg)

**Comment by methnen** [comment]
This looks like Highcharts? 

My guess is that your theme has some CSS somewhere that's targeting Highcharts elements and that's what's going on.

Can you try temporarily switching themes to something more basic and seeing if that fixes it?

**Comment by McCoyCOREUSA** [comment]
I've tried all of them. Exact same results.

**Comment by methnen** [comment]
Any chance this is up on a staging server or somewhere I can take a look?

**Comment by McCoyCOREUSA** [comment]
Sorry no it's on a live site

**Comment by methnen** [comment]
Able to put a private page up with some charts in it?

I can see what I can figure out that way probably.

**Comment by McCoyCOREUSA** [comment]
URL: Route66Community.com
UN: tempuser@mccoycore.com
PW: 92929

Sample Page with two charts: https://route66community.com/test-chart/

**Comment by methnen** [comment]
OK,

So there are a bunch of styles in your core theme pointing at Highcharts related stuff. But I don't think they're the root of the issue.

Some examples:
https://route66community.com/wp-content/themes/alliance/skins/default/css/__plugins.css
https://route66community.com/wp-content/themes/alliance/skins/default/plugins/m-chart/m-chart.css

I'm a bit baffled actually after looking at it. I the javascript settings for the pie chart are definitely set to "pie" not "donut" like it's being displayed.

And the the column chart has no settings that should be overriding the column width in that manner. There's plenty of room for the default Highcharts stuff to calculate a thicker column.

I'm thinking there's gotta be something still in the theme though (maybe some custom Javascript?) that's causing this. I'd recommend going to the Highcharts support for this as whatever is happening I'm pretty sure it's happening in their rendering engine not in the M Charts stuff.

**Comment by McCoyCOREUSA** [comment]
Thank you. So, Highcharts is something separate from the plugin?

**Comment by methnen** [comment]
Yes, and its licensing is very different from the Chart.js rendering that's default in the plugin. That's why I had to split it out of the core plugin. WordPress.org requires GPL compatible license and Highcharts license is not GPL compatible.

Highcharts is extremely mature and has a ton of features and stuff it can do though so if your website fits within the licensing structure it is the more robust of the two rendering engines.

The Highcharts website is here:

https://www.highcharts.com

Chart.js is the default rendering engine and it has an MIT license same as the plugin so it's going to have basically no licensing restrictions that would likely affect you.

https://www.chartjs.org
