### ISSUE TITLE
How to add other settings in the theme file? Eg. padding for title

### ISSUE THREAD

**Issue by bguanorigin** [methnen/m-chart#175]
Thank you for making the plugin!

I am trying to figure out how to add paddings under the title. I don't know how exactly to apply the options in Charjs' doc to the theme file. 

```
return array(
	'colors' => array(
		'#2267b5',
		'#d94364',
		'#dbcc3d',
		'#008BA3',
		'#00bcd4',
	),
	'title' => array(
		'padding' => array(
			'bottom' => 30
		)
	)
);
```
How to make something like above work? (The title part)

**Comment by methnen** [comment]
You have to match the way Chart.js expects it. 

So for Chart.js the title docs are here:

https://www.chartjs.org/docs/latest/configuration/title.html

Note that the title stuff is all under options -> plugins.

So you'd want something like this:

```php
return array(
	'colors' => array(
		'#2267b5',
		'#d94364',
		'#dbcc3d',
		'#008BA3',
		'#00bcd4',
	),
	'plugins' => array(
		'options' => array(
			'title' => array(
				'padding' => array(
					'bottom' => 30,
				),
			),
		),
	),
);
```

Also just a word of advice with PHP and arrays (which is what these are), unlike with Javascript objects you can go ahead and always put a comma even after the last item in the array. Doing that can save you from silly mistakes later on.

**Comment by methnen** [comment]
Gonna close this as answered but feel free to follow up with any other questions in here. :)
