### ISSUE TITLE
Multiple charts on a query posts

### ISSUE THREAD

**Issue by marcioc0sta** [methnen/m-chart#34]
Hi there,first, congrats!!! the plugin is awesome!

But, today i tried to make a query with two posts, both posts have graphs but only one have been printed (the last), u have any suggestion?

**Comment by methnen** [comment]
Hey @marcioc0sta is it possible that the first chart isn't published?

**Comment by methnen** [comment]
@marcioc0sta I'm still pretty sure that what you're dealign with is a chart that hasn't been published yet.  But your issue report prompted some investigation that discovered a related bug that's been fixed in 1.1.2.  Please update to that one and let me know if you're still having any problems.

**Comment by marcioc0sta** [comment]
Hi @methnen thanks to the fast feedback =]
Both graphs have been published, but, i'll update the plugin to see whats happen. Again, thanks for the  help.

**Comment by marcioc0sta** [comment]
@methnen, i'm very grateful, the problem have been solved!!!

THANKS!

**Comment by methnen** [comment]
@marcioc0sta Glad that fixed things. And very glad you're enjoying the plugin.
