### ISSUE TITLE
(Bar chart) Uncaught TypeError: Cannot read property 'defaultView' of undefined

### ISSUE THREAD

**Issue by arnaudcrowther** [methnen/m-chart#43]
Unable to create a simple bar chart, all other chart types are working well

Data example:

+-----------------+
November
+-----------------+
9
+-----------------+

Options: 

Type: bar
Parse: row

Example link: http://hartmedical.org/m-chart-test/

Thank you

**Comment by methnen** [comment]
Hey @arnaudcrowther I'm actually seeing a working chart there.

Was there a line given in the error possibly?

I'll see if I can reproduce the issue on my end.

**Comment by arnaudcrowther** [comment]
Thanks for the quick answer @methnen !

I had accidental changed the wrong chart, please check again

**Comment by methnen** [comment]
Yeah, that doesn't look awesome.  Can I get you to take a screenshot of both data and the settings you have set and either attach them to this ticket or email them to me at jamie AT methnen.com?

**Comment by arnaudcrowther** [comment]
Another important note: when I create the chart, the preview renders correctly which leads me to believe there is some js conflict on my live version. Which is odd since all the other chart types render correctly on both preview version and live version. 

Just sent you the screenshots to your email.

Thanks!

**Comment by methnen** [comment]
Weird. So in the admin panel the graph is working. If you switch to parse data in columns it should look correctly at least. But that doesn't explain why it's not working in the page. I've reproduced the issue and will let you know what I find. Thanks for the bug report.

**Comment by methnen** [comment]
Yeah, huh.  I'm pretty convinced at this point that it's some sort of conflict in the Highcharts library itself that's causing the Javascript exception. I'm going to try upgrading Highcharts on my end and seeing if that solves it.  If not I'll likely have to file a bug report with them.

Stay tuned.

**Comment by methnen** [comment]
Alright, updating to the latest version of Highcharts seems to sole the problem. I'll push a new version of M-Chart today that should solve your issue.

**Comment by arnaudcrowther** [comment]
Thank you so much!

Ill keep my eyes open for the Wordpress plugin notification.

**Comment by methnen** [comment]
@arnaudcrowther the new version is up.
