### ISSUE TITLE
Save draft and publish buttons grey out

### ISSUE THREAD

**Issue by AtlasRush** [methnen/m-chart#46]
Hi, I'm suddenly having problems with M Chart after a few months of use.
Now, when I create a chart and start putting datas in the chart sheet, Save draft and Publish buttons grey out, and they don't allow me to click on them anymore.
I tried bypassing through Dev console from Chrome deleting "disabled" from the line of code of the buttons but it just doesn't save.
It's a new thing for me, it never happened. Does it have something to do with Jetpack and/or some of its functions?

**Comment by methnen** [comment]
Every time you edit the spreadsheet or change a chart setting, there's a short period of time where the Save Draft/Publish buttons will become disabled while the plugin regenerates the image version of the graph and updates a few values that are needed on save.  It's basically identical to how the WP post autosave stuff works.

Once that's finished the buttons get re-enabled.  It sounds like something is preventing that for some reason.  I've never seen Jetpack cause that sort of issue but I suppose it's possible.

Can I get a list of the plugins you are using as well as the version of WP that you are currently on and I'll see if I can duplicate the issue.

**Comment by methnen** [comment]
And yes, I'm apparently answering bug reports on Christmas.

**Comment by AtlasRush** [comment]
1st reply: Oh, I see. It looked like the server resources were saturated, not it's working fine. Thanks a lot and merry christmas.
P.S.: your plugin is WONDERFUL.
You can see it used on ReHWolution.it ;)

**Comment by methnen** [comment]
Ah, good to hear all is good. And glad you enjoy the plugin. :) Always nice to see it getting used.
