### ISSUE TITLE
a user's suggestion

### ISSUE THREAD

**Issue by 3298021** [methnen/m-chart#47]
i'm a over sea user from china, so maybe some wrong words here...
recently use your wonderful plug-in m-chart and have some suggestion below
1.gave the "lang" dir and en-us.pot, so everyone can help you tarnslate your plug-in;
2.have a opinion which can do Linear data comparison by mouseover or single touch on smartphone, just like the plug-in "chart-expert" at http://pmzez.com/plugins/chart-expert/ with "c3" project at http://c3js.org/ ;
3."c3" also have a timeout opinion which can do chart animation and you can find the demo at http://c3js.org/, i don't know whether the "highchart" can do it, but it's just a suggestion. 
e.g, we change the "Data" banner on the "Add Chart" page into two or more Data banners with can help doing chart animation;
4.change the "image" optional, i just think every chart have a png file is a bit useless for me;
5.have a single access control opinion to control which type of users can create charts, or which can see the chart

just suggestion, a fun user with thanks

**Comment by methnen** [comment]
Hey thanks for the suggestions! And glad you like the plugin.

My wife actually speaks/reads Chinese fluently so it might be easier for you to post that in Chinese and then she can explain to me what you said. I'll admit I don't immediately follow all of your suggestions though I think I understand some of them.

I'm very interested in having the plugin translated and the first steps for that are already in the code. But yes an english lang file for people to start with would be great.  

I'm planning to work on adding some new features that have been suggested by users next month while I'm trapped on an airplane to China for 17 hours so I'll have some time to address some of this stuff soon.

**Comment by methnen** [comment]
Closing.
