### ISSUE TITLE
How to deactivate image output

### ISSUE THREAD

**Issue by AtlasRush** [methnen/m-chart#48]
Hi, it seems like I'm having the same problem again, and probably it depends on the fact that M-Chart also generates a static picture together with the chart. Is there any way to turn this feature off? Like, I only use charts, not pictures.
Thanks in advance!

**Comment by AtlasRush** [comment]
Hello? (It's me)

**Comment by methnen** [comment]
Hey @AtlasRush sorry, on weekends I try to focus on family as much as possible.  I'm pretty sure a small part of the image generation is the issue as you're guessing.  There is not a way currently to disable that feature but you are the second person to ask for it so it's safe to say I'll be adding that as a feature in the next version.

I'll admit it's large enough change it's not something I can throw together extremely quickly so it's going to be something I'll have to address when I have more time (I've got a day job that's keeping me very busy right now).

However, I'm planing to set aside a few days earlier next month to add some of the more requested larger features that people have asked for and this will be one of them.

Also I've been thinking about the issue and there's also a way to possibly work around it so the server processing the spreadsheet data is no longer a bottle neck or at least becomes less of one. If I have a small moment over the next week or so I'll try to see if that might work and if so possibly get that smaller fix in earlier.

**Comment by AtlasRush** [comment]
I appreciate the work you put in it, and I didn't mean to sound rude. It's just that I was really excited using your plugin in these weeks, but now, with some particular charts that are a bit bigger in columns and datas, it gives me problems. Always the "greyed out" buttons, as you may guess. Isn't there a way to temporarily disable it even though it's not something permanent? Or maybe something to // comment in order to skip it? I really can't wait 1 month for a fix, I'd be forced to go back to swf charts :\

**Comment by methnen** [comment]
You can try this, I can't so for sure that it won't break something important though.

Open up the admin JS file:

/components/js/m-chart-admin.js

The look for the `m_chart_admin.refresh_chart` function and directly above this line:

`m_chart_admin.refresh_counter++;`

Put this:

`return false;`

**Comment by methnen** [comment]
As I think about it, this will probably work, but it will create a situation where to see the changes you've made reflected in the chart you'll have to save the chart.

**Comment by AtlasRush** [comment]
Like this?
http://imgur.com/AdMuZKP
regarding the saving thing, I wouldn't care, all I need is the charts to be rendered properly with new datas (I write reviews about hardware and stuff, charts for a me are really important).

**Comment by methnen** [comment]
Yep that's it.

**Comment by AtlasRush** [comment]
It gives me a 404. It doesn't seem like it's the server limiting my resources, though..

**Comment by methnen** [comment]
There no reason I can think of that that change should be causing a 404.

Where do you get the 404 error? One the chart edit page?

**Comment by AtlasRush** [comment]
When I save the draft or publish the chart

**Comment by methnen** [comment]
I just tested the change on my dev machine and I can't duplicate any 404 on save issues though I do get the behavior I thought we would (the chart will only reflect changes after having saved it).

Is it possible that you are having some performance issues unrelated to the plugin?

**Comment by AtlasRush** [comment]
Yep, that's why I was asking if there was a way to skip the PNG generation process... I'm figuring out if it's about permalinks (i changed the structure) and drafts previously saved to the permalink changes.

**Comment by AtlasRush** [comment]
It looks like it's not about permalinks. I just tried creating new chart drafts and nothing changes. I really don't know...

**Comment by methnen** [comment]
404 on save is literally implying that the server can't find the target of the save post form.  Which is hard to believe.  Are there any server folks you can talk to that can possibly look into it? I'm pretty sure at this point that the plugin isn't in play here.

**Comment by AtlasRush** [comment]
Ok, If I don't make any change AND save or publish, it works. If I add a row to the datas, it goes 404...

**Comment by methnen** [comment]
Can you export the the data as a CSV file and attach it with a screenshot of the form settings to this ticket? I'll try to replicate your conditions exactly.

**Comment by AtlasRush** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/16438961/12241904/4211dd5c-b896-11e5-8b62-9d46115c6e13.jpg)

**Comment by AtlasRush** [comment]
Sorry, I thought I could upload the CSV file too. Here it is: https://mega.nz/#!ZhB32aiL!wRqxlwsuU8-rbPtD4H9C8izMopocLIZT3SoR7sAq7EI

I removed a line, and the saving feature worked. I tried to add it back, and again a 404. WTF?

**Comment by methnen** [comment]
Thanks, I wish I could say I was able to duplicate the issue you're experiencing.  But I was not.  

I'm assuming you're running the latest version of M Chart and with that version and the hack applied I'm not experiencing any issues adding lines to the chart you're working with (despite using exactly the same data and the same settings).

**Comment by AtlasRush** [comment]
I'm on a sh*tty server that is probably limiting my resources. I'll end up getting a new one before the end of the week, probably. It's the only variable (apart from me being useless when it's about coding) that should be responsible of those errors.
Do you have any way of looking into it if I give you my website credentials?
Thanks again, Jamie, you're really kind.

**Comment by methnen** [comment]
I could possibly take a look later tonight or tomorrow.

If you'd really like. However, if this is just run of the mill server performance problems there's basically nothing I can do.

**Comment by AtlasRush** [comment]
Ok, here's the thing: my hosting provider limited the number of cgi and php scripts I can execute :(

**Comment by methnen** [comment]
That certainly explains some things.

**Comment by AtlasRush** [comment]
I'm talking with 1&1 in these days to get a bigger server compared to the one with our current hosting provider. We'll go from 1 vcore/1gb RAM to 4 vCore 4GB RAM, hoping that'll be enough! HUGE, HUGE thanks for your patience and kindness.

**Comment by AtlasRush** [comment]
Hi Jamie, with the new hosting we're not having problems at all. It was netsons (that limited our resorces) to make us go 404's.
Now I reset the refresh_chart thing, and I can work smoothly :+1: 
I'll modify the chart colours now, following one of the threads here :) Thank you really much!
