### ISSUE TITLE
WP 4.5 and Future WP Version Compatibility

### ISSUE THREAD

**Issue by OurWeb** [methnen/m-chart#51]
Hi Methnen,

I need to know if you will be keeping M-Chart up-to-date with the latest WP updates? 

So far it's broken on WP 4.5, since it doesn't display the chart in the admin anymore.

This is very discouraging since I've already create 50 charts with your plugin and I can't upgrade my WP until the plugin is compatible. 

So do you intend to keep it up-to-date???

Thanks,
OurNet

**Comment by methnen** [comment]
Hey @OurWeb I'm a single dev with a full time job. I'm doing my best to keep things up to date though. I'm taking a look at the WP 4.5 issue tonight and will hopefully have a fix up shortly.

**Comment by methnen** [comment]
Hmm.... I'm unable to duplicate any issues with charts showing up in the admin panel on WP 4.5 or WP 4.5.1.

Is there a time tomorrow or sometime this week that you might be able to provide some more details on what exactly might be happening. I'd especially be interested in any errors that might be showing in the browser's console window.

**Comment by OurWeb** [comment]
Thanks for following up, Jamie. The issue resolved itself when I updated my Theme, so I guess the out of date theme was interacting with 4.5 in a way that blocked the display of the chart. Case closed :)

**Comment by methnen** [comment]
Ah good. Just FYI I do try to always spot check releases to make sure nothing important is broken before a major WP release. And I did do that with the plugin. I don't always manage to update the plugin read with this information though.
