### ISSUE TITLE
User suggestion

### ISSUE THREAD

**Issue by robmcclel** [methnen/m-chart#52]
@methnen ,

I was looking for a data visualization system for my users and came across this plugin.  I was really impressed by the Edit chart screens that showed the data table and the chart together on the back end.

Every other visualization plugin I've seen ports everything to the front end -- but I'm looking for a data dashboard system that is entirely in the back end dashboard.  Something I can pre-set up and just have users upload data to.  My specific need is Amazon KDP CSV data (sales analysis), but I'm sure others have other needs.

Is this a possible development direction for this plugin?  A back end data analysis dashboard?

I know for my niche users, having everything on the front end isn't ideal for them.  They would prefer their data remain inside the site unless they choose to share it.

Thanks!

**Comment by methnen** [comment]
Hey @robmcclel 

That's a cool idea but it's probably another product entirely. There's definitely overlap though and I can conceive of how you might use some of the action and filter hooks to create something along those lines as an add on plugin.  

If you decided to try tackling that and needed a hook in a place that one doesn't exist I'd be happy to add any you needed.  I'm not sure how comfortable you are doing that sort of plugin development but here's a link to the dev documentation on the currently available hooks:

https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks

**Comment by methnen** [comment]
Closing because this is out of scope with my current intentions for the plugin.
