### ISSUE TITLE
Add method for duplicating charts

### ISSUE THREAD

**Issue by methnen** [methnen/m-chart#56]
Thinking this would work well as an additional inline edit control from the charts list.

Extracted from this issue:

https://github.com/methnen/m-chart/issues/50

**Comment by AtlasRush** [comment]
I use a plugin to clone posts and it lets me clone charts automatically :)

**Comment by methnen** [comment]
@AtlasRush is this the one?:

https://wordpress.org/plugins/clone-posts/

**Comment by AtlasRush** [comment]
I'm using this one: https://wordpress.org/plugins/duplicate-post/

**Comment by methnen** [comment]
Closing this issue:

https://github.com/methnen/m-chart/wiki/Duplicating-charts
