### ISSUE TITLE
multiple data series into the same chart

### ISSUE THREAD

**Issue by rey2204** [methnen/m-chart#60]
I entered three columns of information: date, series 1 data, and series 2 data.  However, I am unable to get multiple data series into the same chart.  Also, the legend just says "series 1" instead of the column header name.  I feel like I'm missing something obvious, but I'm unable to figure it out.

Thanks for the help.

**Comment by methnen** [comment]
Hello @rey2204 happy to help out. Without seeing the data set and the settings you are trying to use I can't help much though.

If you use the CSV export feature and then attach the file along with a screenshot of the chart settings to this issue I should be able to help you out.

**Comment by rey2204** [comment]
Thanks for the reply.  I tried it with and without the CSV import feature and it didn't work either time - that file is attached as an Excel file (wouldn't let me attach a .CSV file).  Also attached a screenshot of  the settings.  Here's a summary of the settings:

Type: Line
Theme: Highcharts 4.x
Height: 400
Parse data in: Rows
Show labels: yes
Show legend: no (though I would choose yet if I could have two data series)


![screenshot](https://cloud.githubusercontent.com/assets/19214644/15194597/726f5970-1778-11e6-988e-ce49b6acc6cc.png)

[us gdp chart test.xlsx](https://github.com/methnen/m-chart/files/260127/us.gdp.chart.test.xlsx)

**Comment by methnen** [comment]
@rey2204 This was thankfully an easy one.

Remove the contents of the first cell and switch the parsing to columns.

That should give you what you want.

**Comment by rey2204** [comment]
Awesome, thanks for your help!
