### ISSUE TITLE
Chart Shortcode Not Displaying

### ISSUE THREAD

**Issue by shengyilee** [methnen/m-chart#62]
Hello,

I've created and saved my chart however when I apply the shortcode to a new blog post in Wordpress it doesn't display the chart.

This is the original chart: http://secretagent.com.au/chart/inner-north-housing-index/
And this is where I want it to appear (Below the "What We Do" section): http://secretagent.com.au/test/

Also, in what conditions does the chart display as a PNG instead of an interactive graph?

Thank you!

**Comment by methnen** [comment]
Hey @shengyilee were you able to get this to work? I'd be happy to took but not seeing any M Chart code on that page.

In answer to your second question, it gets used in RSS feeds where Javascript won't function.  But it can also be forced by setting `img="yes"` on the shortcode: `[chart id="12" img="yes"]`

**Comment by camilawaz** [comment]
I have the same problem. @methnen 

The console is pointing out the error: Uncaught TypeError: $(...).highcharts is not a function

Here's a live example: http://estudiodoiscafes.com.br/pautanegocios/post-com-grafico/

The theme is a personal theme which I created to a client. I have the plugin working fine in other project using the Divi Theme. 

You can help me to figure this out? Thanks

**Comment by methnen** [comment]
Hey @camilawaz I just tried to take a look but the shortcode isn't being processed. Is the plugin active at the moment?

**Comment by methnen** [comment]
FYI I've got a new version of the plugin I'm hoping to launch sometime in the next few days. It will have an option to run the embeds via iframes which I'm hoping will prevent these types of theme issues some people have had.

**Comment by camilawaz** [comment]
Sorry, my bad! 
It's now active :)

**Comment by methnen** [comment]
@camilawaz 

This issue when it crops up is always "weird" it's acting like the highcharts.js file isn't included in the page but it is there I can see it.  

Try calling this in your theme as early as possible, ideally when the `wp_enqueue_scripts` gets called. Your theme may already have a method hooked up to that as it's the ideal time to call any theme scripts.  This should force highcharts to load as early as possible maybe avoiding the error.

```php
wp_enqueue_script(
	'highcharts',
	'http://estudiodoiscafes.com.br/pautanegocios/wp-content/plugins/m-chart/components/external/highcharts/highcharts.js',
	array( 'jquery' ),
	false,
	false
);
```

**Comment by camilawaz** [comment]
Work :) 
Thank you! 
I'll be waiting the new version. 
Congrats for the awesome plugin!

**Comment by methnen** [comment]
Awesome. 👍
