### ISSUE TITLE
New Translation Ver.

### ISSUE THREAD

**Issue by 3298021** [methnen/m-chart#65]
Yesterday, I just have some free-time and translate the unfinished Chinese po
How to send it to you?
m-chart@noreply.github.com , this one may not work

**Comment by 3298021** [comment]
Oh, i just remember that 
Can you give an "Original" opinion in the "Type" which can display the original chart ?

**Comment by methnen** [comment]
@3298021 Do you know how to use github? You could just send a pull request.

Otherwise please email it to me at jamie AT methnen.com

**Comment by methnen** [comment]
@3298021 thanks a ton for the translation.
