### ISSUE TITLE
Allow custom vertical axis minimums

### ISSUE THREAD

**Issue by methnen** [methnen/m-chart#67]
Switch out the current *Force vertical axis minimum to zero* toggle with one that allows a custom value.

**Comment by methnen** [comment]
Added in 1.4.

**Comment by dribanig** [comment]
I do like this change but how about a maximum value as well. Also I would love to be able to flip the vertical axis and have the minimum at the top.  I am displaying a sports ladder and having it run from 10 to 0 when it should run from 1 to 9 is a bit strange!

**Comment by methnen** [comment]
Flipping the axis has been requested before. I'll probably add that officially sometime soon.

There's a way to hack it using the themes though:
https://wordpress.org/support/topic/vertical-axis-reverse-order?replies=5

You've actually got the first example of why anyone would want a max axis value. Highcharts does support that. 

In the meantime you could do a similar hack for the max setting to the vertical axis reverse one if you wanted. Maybe name the theme Sports Ladder:

```php
<?php

/**
 * Theme Name: Sports Ladder
 */

return array(
    'yAxis' => array(
        'reversed' => true,
        'max' => 9
    ),
);
```
