### ISSUE TITLE
Undefined property: M_Chart_Highcharts::$get_chart_args

### ISSUE THREAD

**Issue by MWDelaney** [methnen/m-chart#68]
Hi,
I love this plugin, but when saving a chart I get the following error:

````
Notice: Undefined property: M_Chart_Highcharts::$get_chart_args in /path/to/mysite/wp-content/plugins/m-chart/components/class-m-chart-highcharts.php on line 193
````

Commenting out line 193 seems to resolve the issue, but that probably isn't what we want to do. Reading through that class it looks like there isn't a local method `get_chart_default_args`.

If there's anything I can do to help troubleshoot, let me know!

**Comment by methnen** [comment]
Hey @MWDelaney 

Thanks for the bug report you are correct there's an issue there. I somehow wasn't getting that notice but I can see how it would happen. I'll have a new version that corrects this up soon.

**Comment by methnen** [comment]
And the new version should be up on wordpress.org shortly.

Thanks again fro the bug report.

**Comment by MWDelaney** [comment]
Hi, methnen, thank you for fixing this so quickly. I'm getting another similar warning with the new version:

````
Notice: Undefined property: stdClass::$post_title in /path/to/mysite/wp-content/plugins/m-chart/components/class-m-chart-highcharts.php on line 108

````

This is another case where it looks like `$this->post` isn't defined at this point in the script.

Let me know if I can help troubleshoot at all.

**Comment by MWDelaney** [comment]
If it helps my development environment is [Roots/Trellis](https://roots.io/trellis/). It's annoyingly good at displaying errors!
