### ISSUE TITLE
Same shortcode in post

### ISSUE THREAD

**Issue by espilber** [methnen/m-chart#71]
Hi, I'm trying use the same shortcode (id) twice in one post (one shortcode in content and the second shortcode on a hidden div (hidden by default, but visible in certain situations). Only works one shortcode, the second doesn't works. I have other shorcodes with diferents ids and I have no problem.

Maybe a  quick fix is duplicate chart option...

Thanks for that awesome plugin!

**Comment by methnen** [comment]
Hey @espilber you've run into a use case that I admittedly never anticipated.

I'll have to think about how I might solve it. The code relies on the chart id's to differentiate between the different charts on a given page and a duplicate would obviously need to be differentiated in some other way.

I'll probably have to add an instance value that gets tacked on somehow.  

I'll get back to you in a few days when I've had some time to further ruminate on it.

**Comment by methnen** [comment]
Fixed in 1.4.1
