### ISSUE TITLE
Can't get the chart to work with web base spread sheet.

### ISSUE THREAD

**Issue by gracedigital** [methnen/m-chart#72]
I tried using Google Docs Spreadsheet and also posting a CSV to dropbox but neither will render.  Is this supposed to be able to work with online spreadsheets?

**Comment by methnen** [comment]
Hey @gracedigital you can import CSV files but you can't link to one that's online somewhere. There's no interface or backend for that.

As for a specific CSV file rendering I'd need to see how it's formatted to know what might be wrong.

If you'd like to send it my way and send me a screenshot of the settings you're using for your chart I'd be happy to take a look:

jamie at methnen.com

**Comment by gracedigital** [comment]
It works when I manually import.  I’m curious then what is the Source URL parameter is for?

[cid:D4E2EE08-C536-4B05-8885-434E5FAF7238]

**Comment by methnen** [comment]
Ah. That's for making the source text clickable. So if you want to indicate where the data is from with a link.

**Comment by gracedigital** [comment]
Ok. Thanks!

**Comment by gracedigital** [comment]
Also, is it possible to have the graph just show the top “N” values?

**Comment by methnen** [comment]
Hey sorry just noticed the follow up question. I'm not sure what you mean by only showing the top N value.  

Can you clarify a bit?
