### ISSUE TITLE
Charts not showing on various sites with WP 4.6.1

### ISSUE THREAD

**Issue by gocemitevski** [methnen/m-chart#77]
Hi Jamie,

Thanks for developing this great plugin. Did you had any chance to test it on the latest version of WordPress? I'm experiencing issues with the showing of the charts on several different websites. The markup is there, but the charts are not showing on the front-end. The are visible while editing in the back-end.

**Comment by methnen** [comment]
Hey Goce.  Yes I've tested it on the latest version of WP 4.6.1 and didn't see any issues. I'm unable to replicate any problems displaying charts on the front end as well.

Chances are, if the code is in the page, but the chart isn't showing that there's some sort of JS conflict. Is there a publicly accessible URL can provide where I can observe the problem?

If you want to send a URL more privately feel free to email me:

jamie AT methnen.com

**Comment by gocemitevski** [comment]
@methnen thanks for the prompt reply. You're right. I did more testing on several more different setups and the graphs were rendering without problems. I will let you know when I find the specific cause.

**Comment by methnen** [comment]
@gocemitevski Please do let me know if/when you find the what was conflicting with the plugin. I would like to try and prevent the issue if possible.  In the meantime I'm closing this.
