### ISSUE TITLE
Improvement: Add Toggle to Enable Shared Tooltips

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#83]
M-Charts would benefit from adding a per-chart preference toggle to enable shared tooltips:

    {
        tooltip: {
            shared: true
        }
    }

This displays all of the tooltips on a single shared tooltip when mousing over the series, as opposed to the default setting of showing only the currently active series in the tooltip. Depending on the graph implementation, either case could be desirable.

**Comment by methnen** [comment]
Great idea. I'll look at doing this in a future version.

**Comment by methnen** [comment]
Closing as relevant issue is addressed in 1.6.
