### ISSUE TITLE
Regional settings

### ISSUE THREAD

**Issue by martin8032** [methnen/m-chart#85]
Currently the plug-in always uses a comma to group numbers (i.e. 127,238). This is not suitable for countries like Germany (they use a period for this purpose, i.e. 127.238) oder Switzerland (where an apostrophe is used, i.e. 127'238).

May I suggest to add some kind of regional settings where you can modifiy this separator?

**Comment by methnen** [comment]
Great idea Martin. I'll make sure this makes it into the next version.

**Comment by methnen** [comment]
Closing as relevant issue is addressed in 1.6.
