### ISSUE TITLE
Replace getExtension() with getFilename() to Improve Compatibility

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#86]
I need to install m-chart on a Wordpress installation using an older version of PHP (5.3.2) that I am unable to update. The plugin fails on the getExtension() method of a DirectoryIterator of the M_Chart_Highcharts class . Replacing

    434    if ( ! $file->isFile() || 'php' != $file->getExtension() ) {

with

    434    if ( ! $file->isFile() || ! preg_match( '/.php$/i', $file->getFilename() ) ) {

solves the problem. The simple RegEx has minimal impact on page performance.

**Comment by methnen** [comment]
@buffaloseven I'll make sure to put this in the next version.

I sadly can't say when I'll be able to get it released though. I had hoped to have it finished by the new year but paying work has gotten in the way. Hopefully sometime near the end of January but no promises.

**Comment by methnen** [comment]
Feel free to hack the current one on the site in question though, knowing that the next release will include your fix.

**Comment by buffaloseven** [comment]
No problem on the updates.

I assume that change will work in all cases; it just checks to see if the filename ends in .php, which should accomplish the same as the getExtension() function.

**Comment by methnen** [comment]
Closing as relevant issue is addressed in 1.6.
