### ISSUE TITLE
Feature Request: Create Templates 

### ISSUE THREAD

**Issue by mshigekawa** [methnen/m-chart#88]
It would be cool if you could save a table as a template, then when you create a new chart, you could load that template to pre-fill the table. Also being able to clone charts.

**Comment by methnen** [comment]
@mshigekawa can you clarify that first part of the request? Do you mean you would like if there were a way to create a chart and have the HTML table version of it get auto generated as a page/template type or something along those lines?

I've decided that cloning charts is outside of the scope of the plugin. There's plenty of existing post cloning plugins. I've been told this one works great with M Chart: https://wordpress.org/plugins/duplicate-post/

**Comment by mshigekawa** [comment]
I envision having Personal Trainers creating a standard set up tables/charts (i.e. Client Measurements) like the one below for each of their clients. Instead of them having to create a new chart each time for their clients and copying and pasting those row values, it would be convenient to have a "save as template" and "load template" feature.

![screen shot 2017-02-02 at 4 32 12 pm](https://cloud.githubusercontent.com/assets/21282923/22574686/37352974-e965-11e6-999d-f3512b655a96.png)

**Comment by mshigekawa** [comment]
Having just installed Duplicate Post per your recommendation, this actually allows a pretty good workaround in which I can just create "template" charts, lock them, then have the user clone the chart. This solution would be good enough. Thanks
