### ISSUE TITLE
Customizing the Single Chart Display Page

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#98]
I was wondering where exactly the code is that configures how the single-chart view (e.g. this [temperature graph](https://www.aweathermoment.com/chart/2017-annual-temperatures/)) is configured.  I'd like to apply a few custom elements to the page but — perhaps because I'm sleep deprived and just praying my youngest will sleep — can't seem to find it.

Related to that, it could be nice for the charts to have a _caption_ and _description_ meta field.  Perhaps with a toggle, the _caption_ could be displayed underneath the chart when it's embedded in a page/post, and the _description_ could be presented as rich text underneath the graph on the single-chart view.

EDIT: Thought would be that caption is plain-text and description is the full WYSIWYG editor.

Thoughts?

**Comment by oddtober** [comment]
If you are adding the caption and description underneath, then would a normal text before the shortcode suffice?

**Comment by methnen** [comment]
Where the front end view is built? You'll see a a `get_chart` method in the `class-m-chart.php` file.

That gets the chart code. You'll see get the chart arguments and then inserts them into a template file `highcharts-chart.php`.

I don't think they exist in the current version but in my dev copy that will become 1.6.3 has action hooks before and after the template file is loaded that would potentially allow you to put stuff before and after quite easily.

**Comment by methnen** [comment]
@buffaloseven I've added action hooks that address your need here in version 1.7. I haven't documented them yet but look here and you'll see action hooks before `get_chart` does it's thing and after the template is called in `get_chart`:

https://github.com/methnen/m-chart/blob/master/components/class-m-chart.php#L443
https://github.com/methnen/m-chart/blob/master/components/class-m-chart.php#L510
