### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by jonhyleo** [methnen/m-chart#99]
At the time of creating a graph, I can visualize it in real time in the post editor window. But, when I publish it, I can only see the generated PNG image and where it should be the graph appears a warning of Error 404.

I have reviewed the structure of the permanent links and everything seems to be correct.

I am running the tests on a local server with php v5.6, MySQL 5.6.35, in macOS Sierra with the application MAMP PRO.

The version of Wordpress is 4.8.2 and I am using the Newspaper v8.1 theme.

Thanks in advance.

![screen shot 2017-09-19 at 21 32 31](https://user-images.githubusercontent.com/7083143/30621614-81807016-9d82-11e7-8839-5b4667efb4a4.png)
![screen shot 2017-09-19 at 21 32 38](https://user-images.githubusercontent.com/7083143/30621615-8182a5b6-9d82-11e7-92d5-85ff271db4a7.png)
![screen shot 2017-09-19 at 21 33 26](https://user-images.githubusercontent.com/7083143/30621619-8186495a-9d82-11e7-95ba-6e07574b02f6.png)
![screen shot 2017-09-19 at 21 33 49](https://user-images.githubusercontent.com/7083143/30621617-8183f6be-9d82-11e7-948d-c5cc105868b8.png)
![screen shot 2017-09-19 at 21 35 27](https://user-images.githubusercontent.com/7083143/30621618-81852a3e-9d82-11e7-93b7-cc25e4483c7e.png)

**Comment by methnen** [comment]
Hey. I’m not in a good place to look in detail at the moment. However, my immediate guess is the endpoint for charts isn’t triggering for some reason. A sometimes quick fix for that is to refresh the endpoints cache which you can do by visiting the permalinks settings page in the WP admin panel and just hitting the save button. Let me know if that doesn’t fix it and I’ll take a closer look as soon as I can.

**Comment by jonhyleo** [comment]
Hi @methnen, thanks for reply.
I tried to do what you tell me, without favorable results. The problem persists.

I even tried to change the structure of the permalinks and it still does not work :(

**Comment by methnen** [comment]
Was hoping that was the issue. I might actually have a free moment apart from paying work tomorrow where I can look at this in more depth. Are there any hours tomorrow that you might be available in case I need to do some back and forth with you?

**Comment by jonhyleo** [comment]
Sorry for the delay. Yes, i'm available. I'm very interested in resolve the issue. Thanks for your attention

**Comment by methnen** [comment]
Hey, first is the possibly a way you can setup a page/post where I can see the issue in action that doesn't disrupt your visitors?

Also if you want to take this to email please feel free to email me: jamie AT methnen.com

**Comment by jonhyleo** [comment]
Actually i'm testing all tools in a local server. Please let me prepare a environment to share access and notice you when ready.

Thanks!

**Comment by jonhyleo** [comment]
Hi @methnen, i sent you an email.

I see a problem if the check that enable iframe embeds is checked, the chart returns a 404 error.

I tried with this option unchecked and works fine. But, i need that these charts will be embeddable in other sites.

Thanks for your help!

**Comment by methnen** [comment]
Hey @jonhyleo Apologies but I did not get an email from you.

Since it's iframe related I'm strongly suspecting it's related to endpoint still not triggering for some reason. I'll probably need to have some access to your setup to see it happening on the front end for sure and possibly the backend. 

I'll watch for an email, maybe you had a typo in the email?

**Comment by jonhyleo** [comment]
Hi, i sent you the email again.

**Comment by methnen** [comment]
This is fixed in 1.6.3 which was just pushed to Wordpress Plugins.
